module.exports = {
  admin: {
    firstName: 'Tatiana',
    lastName: 'Makosso',
    phone: '0455667788',
    email: 'tatiana.makosso@yopmail.com',
    password: 'azerty',
    user: {},
    token: '',
  },
  coach: {
    firstName: 'Camille',
    lastName: 'Makosso',
    phone: '0455667788',
    email: 'camille.makosso@yopmail.com',
    password: 'azerty',
    user: {},
    token: '',
  },
  customer: {
    firstName: 'Mamadou',
    lastName: 'Seydoukoulibali',
    phone: '0455667788',
    email: 'mamadou.seydoukoulibali@yopmail.com',
    password: 'qwerty',
    user: {},
    token: '',
  },
  contact: {
    email: 'ali.bongo.ondimba@yopmail.com',
    fistName: 'Ali Bongo',
    lastName: 'Ondimba',
    phone: '0455678996',
    user: {},
  },
}
